trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      containerRegistry: 'dockerHubConnection'
      repository: '<DockerHub-username>/my-todo-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

  - task: AzureWebAppContainer@1
    displayName: 'Deploy to Azure App Service'
    inputs:
      azureSubscription: 'azureSubscription'
      appName: 'my-todo-app'
      imageName: 'reyesmelvinr/my-todo-app:latest'